version: '3.3'

services:
  gateway:
    restart: always
    container_name: ca-gateway
    image: lnlscon/epics-ca-gateway:base-3.15-debian-9-test
    env_file:
      - ./ca-gateway-compose.env
    network_mode: "host"
