version: '3.3'

services:
  epics-ca-gateway:
    restart: always
    container_name: epics-ca-gateway
    image: lnlscon/epics-ca-gateway:base-3.15-debian-9
    env_file:
      - ./ca-gateway-compose.env
    volumes:
      - type: bind
        source: ./data
        target: /data
    network_mode: "host"
